// Curated list of universally famous actors for the game
export const CURATED_ACTORS = [
  'Tom Hanks',
  'Leonardo DiCaprio',
  'Brad Pitt',
  'Meryl Streep',
  'Robert De Niro',
  'Al Pacino',
  'Denzel Washington',
  'Julia Roberts',
  'Sandra Bullock',
  'Morgan Freeman',
  'Samuel L. Jackson',
  'Scarlett Johansson',
  'Will Smith',
  'Tom Cruise',
  'Jennifer Lawrence',
  'Matt Damon',
  'Christian Bale',
  'Robert Downey Jr.',
  'Natalie Portman',
  'Johnny Depp',
  'Angelina Jolie',
  'George Clooney',
  'Charlize Theron',
  'Ryan Gosling',
  'Emma Stone',
  'Anne Hathaway',
  'Chris Evans',
  'Chris Hemsworth',
  'Mark Wahlberg',
  'Dwayne Johnson'
]
